spring:
  application:
    name: bbekenov
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: true
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate.jpa.provider: org.hibernate.jpa.HibernatePersistenceProvider

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
  file:
    encoding: UTF-8

server:
  port: ${SERVER_PORT}
  address: 0.0.0.0